/*
 * generated by Xtext 2.10.0
 */
package org.xtext.mdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMDSLScopeProvider extends DelegatingScopeProvider {
}
