/**
 * generated by Xtext 2.10.0
 */
package org.xtext.mdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.mdsl.ui.AbstractMDSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MDSLUiModule extends AbstractMDSLUiModule {
  public MDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
