/**
 * generated by Xtext 2.10.0
 */
package org.xtext.mdsl.scoping;

import org.xtext.mdsl.scoping.AbstractMDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MDSLScopeProvider extends AbstractMDSLScopeProvider {
}
