/**
 * generated by Xtext 2.10.0
 */
package org.xtext.mdsl;

import org.xtext.mdsl.AbstractMDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MDSLRuntimeModule extends AbstractMDSLRuntimeModule {
}
