/*
 * generated by Xtext 2.10.0
 */
package org.xtext.mdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.mdsl.ui.internal.MdslActivator;

public class MDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdslActivator.getInstance().getInjector("org.xtext.mdsl.MDSL");
	}

}
